apiVersion: apps/v1
kind: Deployment
metadata:
  name: claude-code-ui
  namespace: default
  labels:
    app: claude-code-ui
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: claude-code-ui
  template:
    metadata:
      labels:
        app: claude-code-ui
        version: v1
      annotations:
        # Prometheus scraping annotations (if needed)
        prometheus.io/scrape: "true"
        prometheus.io/port: "3008"
        prometheus.io/path: "/metrics"
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        fsGroup: 1001
      containers:
      - name: claude-code-ui
        image: claude-code-ui:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3008
          name: http
          protocol: TCP
        envFrom:
        - configMapRef:
            name: claude-code-ui-config
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /api/health
            port: 3008
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /api/health
            port: 3008
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        volumeMounts:
        - name: claude-projects
          mountPath: /home/claude/.claude/projects
      volumes:
      - name: claude-projects
        persistentVolumeClaim:
          claimName: claude-projects-pvc