apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: claude-code-ui
  namespace: default
  labels:
    app: claude-code-ui
  annotations:
    # WebSocket support
    nginx.ingress.kubernetes.io/proxy-http-version: "1.1"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/upstream-hash-by: "$arg_session_id"
    
    # Enable WebSocket upgrade headers
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "upgrade";
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
    
    # Optional: Enable SSL redirect
    # nginx.ingress.kubernetes.io/ssl-redirect: "true"
    
    # Optional: Configure cert-manager for automatic SSL
    # cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  rules:
  - host: claude-code-ui.example.com  # Change this to your domain
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: claude-code-ui
            port:
              number: 80
  # Optional: Enable TLS
  # tls:
  # - hosts:
  #   - claude-code-ui.example.com
  #   secretName: claude-code-ui-tls