apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: claude-projects-pvc
  namespace: default
  labels:
    app: claude-code-ui
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard  # Change this based on your cluster's storage class