apiVersion: v1
kind: Service
metadata:
  name: claude-code-ui
  namespace: default
  labels:
    app: claude-code-ui
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 3008
    protocol: TCP
    name: http
  selector:
    app: claude-code-ui
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 3600