name: Build and Push Backstage Image

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: depot-ubuntu-24.04,dagger=0.18.12
    permissions:
      contents: read
      packages: write
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=sha,prefix={{branch}}-
            type=raw,value=latest,enable={{is_default_branch}}
            
      - name: Build and push with Dagger
        env:
          DAGGER_CLOUD_TOKEN: ${{ secrets.DAGGER_CLOUD_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Convert tags from metadata action to comma-separated list
          TAGS_JSON='${{ steps.meta.outputs.json }}'
          TAGS=$(echo "$TAGS_JSON" | jq -r '.tags | join(",")')
          
          # Run Dagger build and push
          dagger -m . call build-and-push \
            --source . \
            --registry "${{ env.REGISTRY }}" \
            --image-name "${{ env.IMAGE_NAME }}" \
            --tags "$TAGS" \
            --registry-username "${{ github.actor }}" \
            --registry-password env:GITHUB_TOKEN
          
      - name: Image digest
        run: |
          echo "Image pushed successfully"
          echo "Tags: ${{ steps.meta.outputs.tags }}"
          echo "Labels: ${{ steps.meta.outputs.labels }}"